spring.application.name=Phamarcy-Management-Backend
# QA Environment Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=pharmacy
spring.datasource.username=pharmacy
spring.datasource.password=pharmacy
spring.jpa.properties.hibernate.default_schema=pharmacy
spring.jpa.hibernate.ddl-auto=update
logging.level.root=INFO

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Audit Configuration
spring.jpa.properties.org.hibernate.envers.audit_table_suffix=_audit
spring.jpa.properties.org.hibernate.envers.revision_field_name=revision_id
spring.jpa.properties.org.hibernate.envers.revision_type_field_name=revision_type
spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true

# Logging Configuration for Auditing
logging.level.com.rdp.audit=DEBUG
logging.level.org.hibernate.envers=DEBUG

