-- DROP SCHEMA pharmacy;

CREATE SCHEMA pharmacy AUTHORIZATION pharmacy;

-- DROP SEQUENCE pharmacy.audit_logs_id_seq;

CREATE SEQUENCE pharmacy.audit_logs_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_alert_config_alert_config_id_seq;

CREATE SEQUENCE pharmacy.rdp_alert_config_alert_config_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_alert_logs_alert_log_id_seq;

CREATE SEQUENCE pharmacy.rdp_alert_logs_alert_log_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_billing_items_billing_item_id_seq;

CREATE SEQUENCE pharmacy.rdp_billing_items_billing_item_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_billings_billing_id_seq;

CREATE SEQUENCE pharmacy.rdp_billings_billing_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_categories_category_id_seq;

CREATE SEQUENCE pharmacy.rdp_categories_category_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_customers_customer_id_seq;

CREATE SEQUENCE pharmacy.rdp_customers_customer_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_grn_items_grn_item_id_seq;

CREATE SEQUENCE pharmacy.rdp_grn_items_grn_item_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_grns_grn_id_seq;

CREATE SEQUENCE pharmacy.rdp_grns_grn_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_inventory_items_inv_id_seq;

CREATE SEQUENCE pharmacy.rdp_inventory_items_inv_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_inventory_returns_return_id_seq;

CREATE SEQUENCE pharmacy.rdp_inventory_returns_return_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_products_product_id_seq;

CREATE SEQUENCE pharmacy.rdp_products_product_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_purchase_order_items_poi_id_seq;

CREATE SEQUENCE pharmacy.rdp_purchase_order_items_poi_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_purchase_orders_po_id_seq;

CREATE SEQUENCE pharmacy.rdp_purchase_orders_po_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_roles_role_id_seq;

CREATE SEQUENCE pharmacy.rdp_roles_role_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_store_settings_settings_id_seq;

CREATE SEQUENCE pharmacy.rdp_store_settings_settings_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_suppliers_supplier_id_seq;

CREATE SEQUENCE pharmacy.rdp_suppliers_supplier_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.rdp_users_user_id_seq;

CREATE SEQUENCE pharmacy.rdp_users_user_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE pharmacy.stock_movement_id_seq;

CREATE SEQUENCE pharmacy.stock_movement_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;-- pharmacy.audit_logs definition

-- Drop table

-- DROP TABLE pharmacy.audit_logs;

CREATE TABLE pharmacy.audit_logs (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"action" varchar(20) NOT NULL,
	additional_info text NULL,
	changed_fields text NULL,
	entity_id varchar(255) NOT NULL,
	entity_type varchar(100) NOT NULL,
	http_method varchar(10) NULL,
	ip_address varchar(45) NULL,
	new_values text NULL,
	old_values text NULL,
	operation_description varchar(500) NULL,
	performed_by varchar(100) NULL,
	request_uri varchar(500) NULL,
	session_id varchar(100) NULL,
	"timestamp" timestamp(6) NOT NULL,
	user_agent varchar(500) NULL,
	CONSTRAINT audit_logs_action_check CHECK (((action)::text = ANY ((ARRAY['CREATE'::character varying, 'UPDATE'::character varying, 'DELETE'::character varying, 'VIEW'::character varying, 'EXPORT'::character varying, 'IMPORT'::character varying, 'LOGIN'::character varying, 'LOGOUT'::character varying, 'SEARCH'::character varying, 'BULK_UPDATE'::character varying, 'BULK_DELETE'::character varying])::text[]))),
	CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_audit_action ON pharmacy.audit_logs USING btree (action);
CREATE INDEX idx_audit_entity_id ON pharmacy.audit_logs USING btree (entity_id);
CREATE INDEX idx_audit_entity_type ON pharmacy.audit_logs USING btree (entity_type);
CREATE INDEX idx_audit_timestamp ON pharmacy.audit_logs USING btree ("timestamp");
CREATE INDEX idx_audit_user ON pharmacy.audit_logs USING btree (performed_by);


-- pharmacy.rdp_alert_config definition

-- Drop table

-- DROP TABLE pharmacy.rdp_alert_config;

CREATE TABLE pharmacy.rdp_alert_config (
	alert_config_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	alert_type varchar(50) NOT NULL,
	description varchar(500) NULL,
	enabled bool NOT NULL,
	severity varchar(20) NOT NULL,
	threshold_days int4 NOT NULL,
	CONSTRAINT rdp_alert_config_alert_type_check CHECK (((alert_type)::text = ANY ((ARRAY['EXPIRY_WARNING'::character varying, 'EXPIRY_CRITICAL'::character varying, 'LOW_STOCK'::character varying, 'OUT_OF_STOCK'::character varying])::text[]))),
	CONSTRAINT rdp_alert_config_pkey PRIMARY KEY (alert_config_id),
	CONSTRAINT rdp_alert_config_severity_check CHECK (((severity)::text = ANY ((ARRAY['INFO'::character varying, 'WARNING'::character varying, 'CRITICAL'::character varying])::text[]))),
	CONSTRAINT rdp_alert_config_threshold_days_check CHECK ((threshold_days >= 0))
);


-- pharmacy.rdp_alert_logs definition

-- Drop table

-- DROP TABLE pharmacy.rdp_alert_logs;

CREATE TABLE pharmacy.rdp_alert_logs (
	alert_log_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	acknowledged_at timestamp(6) NULL,
	acknowledged_by varchar(100) NULL,
	alert_type varchar(50) NOT NULL,
	current_stock int4 NULL,
	days_until_expiry int4 NULL,
	expiry_date date NULL,
	message varchar(500) NULL,
	product_code varchar(50) NULL,
	product_id int8 NOT NULL,
	product_name varchar(100) NULL,
	severity varchar(20) NOT NULL,
	status varchar(20) NOT NULL,
	CONSTRAINT rdp_alert_logs_alert_type_check CHECK (((alert_type)::text = ANY ((ARRAY['EXPIRY_WARNING'::character varying, 'EXPIRY_CRITICAL'::character varying, 'LOW_STOCK'::character varying, 'OUT_OF_STOCK'::character varying])::text[]))),
	CONSTRAINT rdp_alert_logs_pkey PRIMARY KEY (alert_log_id),
	CONSTRAINT rdp_alert_logs_severity_check CHECK (((severity)::text = ANY ((ARRAY['INFO'::character varying, 'WARNING'::character varying, 'CRITICAL'::character varying])::text[]))),
	CONSTRAINT rdp_alert_logs_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'ACKNOWLEDGED'::character varying, 'RESOLVED'::character varying, 'EXPIRED'::character varying])::text[])))
);
CREATE INDEX rdp_idx_alert_created ON pharmacy.rdp_alert_logs USING btree (created_at);
CREATE INDEX rdp_idx_alert_product ON pharmacy.rdp_alert_logs USING btree (product_id);
CREATE INDEX rdp_idx_alert_severity ON pharmacy.rdp_alert_logs USING btree (severity);
CREATE INDEX rdp_idx_alert_status ON pharmacy.rdp_alert_logs USING btree (status);


-- pharmacy.rdp_categories definition

-- Drop table

-- DROP TABLE pharmacy.rdp_categories;

CREATE TABLE pharmacy.rdp_categories (
	category_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	description varchar(255) NULL,
	"name" varchar(100) NOT NULL,
	CONSTRAINT rdp_categories_pkey PRIMARY KEY (category_id)
);


-- pharmacy.rdp_customers definition

-- Drop table

-- DROP TABLE pharmacy.rdp_customers;

CREATE TABLE pharmacy.rdp_customers (
	customer_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	address text NULL,
	discount_percentage numeric(5, 2) NULL,
	email varchar(100) NULL,
	"name" varchar(100) NOT NULL,
	phone varchar(20) NULL,
	CONSTRAINT rdp_customers_pkey PRIMARY KEY (customer_id),
	CONSTRAINT uk48jywia10yof5d274fu3sxosr UNIQUE (email),
	CONSTRAINT ukdp80l2pqpgqwqpmhyi837iw9s UNIQUE (phone)
);


-- pharmacy.rdp_roles definition

-- Drop table

-- DROP TABLE pharmacy.rdp_roles;

CREATE TABLE pharmacy.rdp_roles (
	role_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 DEFAULT 0 NOT NULL,
	description varchar(255) NULL,
	role_name varchar(255) NOT NULL,
	CONSTRAINT rdp_roles_pkey PRIMARY KEY (role_id),
	CONSTRAINT ukp8wvm4xgs25tb230j9rui4mnl UNIQUE (role_name)
);


-- pharmacy.rdp_store_settings definition

-- Drop table

-- DROP TABLE pharmacy.rdp_store_settings;

CREATE TABLE pharmacy.rdp_store_settings (
	settings_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	address text NOT NULL,
	email varchar(100) NULL,
	logo text NULL,
	phone varchar(50) NOT NULL,
	store_name varchar(200) NOT NULL,
	tax_id varchar(100) NULL,
	CONSTRAINT rdp_store_settings_pkey PRIMARY KEY (settings_id)
);


-- pharmacy.rdp_suppliers definition

-- Drop table

-- DROP TABLE pharmacy.rdp_suppliers;

CREATE TABLE pharmacy.rdp_suppliers (
	supplier_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	contact_info varchar(255) NULL,
	"name" varchar(100) NOT NULL,
	CONSTRAINT rdp_suppliers_pkey PRIMARY KEY (supplier_id)
);


-- pharmacy.rdp_users definition

-- Drop table

-- DROP TABLE pharmacy.rdp_users;

CREATE TABLE pharmacy.rdp_users (
	user_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 DEFAULT 0 NOT NULL,
	password_hash varchar(255) NOT NULL,
	username varchar(255) NOT NULL,
	address varchar(255) NULL,
	email varchar(255) NULL,
	phone varchar(255) NULL,
	CONSTRAINT rdp_users_pkey PRIMARY KEY (user_id),
	CONSTRAINT uk9ytf236l4cvpgps7p55c37r3s UNIQUE (username)
);


-- pharmacy.stock_movement definition

-- Drop table

-- DROP TABLE pharmacy.stock_movement;

CREATE TABLE pharmacy.stock_movement (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	batch_no varchar(255) NOT NULL,
	from_bin varchar(255) NOT NULL,
	performed_by varchar(255) NULL,
	product_id int8 NOT NULL,
	quantity int4 NOT NULL,
	reference_id varchar(255) NULL,
	reference_type varchar(255) NULL,
	remarks text NULL,
	to_bin varchar(255) NOT NULL,
	price numeric(12, 2) NOT NULL,
	CONSTRAINT stock_movement_from_bin_check CHECK (((from_bin)::text = ANY ((ARRAY['GRN'::character varying, 'INVENTORY'::character varying, 'SOLD'::character varying, 'CUSTOMER_RETURN'::character varying, 'SUPPLIER_RETURN'::character varying, 'EXPIRED'::character varying, 'DAMAGED'::character varying])::text[]))),
	CONSTRAINT stock_movement_pkey PRIMARY KEY (id),
	CONSTRAINT stock_movement_quantity_check CHECK ((quantity >= 1)),
	CONSTRAINT stock_movement_to_bin_check CHECK (((to_bin)::text = ANY ((ARRAY['GRN'::character varying, 'INVENTORY'::character varying, 'SOLD'::character varying, 'CUSTOMER_RETURN'::character varying, 'SUPPLIER_RETURN'::character varying, 'EXPIRED'::character varying, 'DAMAGED'::character varying])::text[])))
);
CREATE INDEX idx_sm_product_batch_date ON pharmacy.stock_movement USING btree (product_id, batch_no, created_at);


-- pharmacy.rdp_billings definition

-- Drop table

-- DROP TABLE pharmacy.rdp_billings;

CREATE TABLE pharmacy.rdp_billings (
	billing_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	billing_date timestamp(6) NOT NULL,
	billing_number varchar(50) NOT NULL,
	discount_amount numeric(12, 2) NULL,
	discount_percentage numeric(5, 2) NULL,
	grand_total numeric(12, 2) NOT NULL,
	is_printed bool NULL,
	notes text NULL,
	payment_method varchar(20) NULL,
	subtotal numeric(12, 2) NOT NULL,
	customer_id int8 NOT NULL,
	CONSTRAINT rdp_billings_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['CASH'::character varying, 'CARD'::character varying, 'MOBILE_PAYMENT'::character varying, 'ONLINE_TRANSFER'::character varying, 'CREDIT'::character varying, 'CHEQUE'::character varying, 'OTHER'::character varying])::text[]))),
	CONSTRAINT rdp_billings_pkey PRIMARY KEY (billing_id),
	CONSTRAINT uk6h9vihameq3tjd4iwi4ccep2w UNIQUE (billing_number),
	CONSTRAINT fk7etx6vmllat1mslxfaoowuwu2 FOREIGN KEY (customer_id) REFERENCES pharmacy.rdp_customers(customer_id)
);
CREATE INDEX rdp_idx_billing_customer ON pharmacy.rdp_billings USING btree (customer_id);
CREATE INDEX rdp_idx_billing_date ON pharmacy.rdp_billings USING btree (billing_date);
CREATE INDEX rdp_idx_billing_number ON pharmacy.rdp_billings USING btree (billing_number);


-- pharmacy.rdp_products definition

-- Drop table

-- DROP TABLE pharmacy.rdp_products;

CREATE TABLE pharmacy.rdp_products (
	product_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	barcode varchar(50) NOT NULL,
	bin_location varchar(50) NULL,
	expiry_date date NULL,
	generic_name varchar(100) NULL,
	max_discount numeric(5, 2) NULL,
	max_stock int4 NULL,
	min_stock int4 NULL,
	"name" varchar(100) NOT NULL,
	patient_instructions text NULL,
	product_code varchar(50) NOT NULL,
	category_id int8 NULL,
	supplier_id int8 NULL,
	CONSTRAINT rdp_products_min_stock_check CHECK ((min_stock >= 0)),
	CONSTRAINT rdp_products_pkey PRIMARY KEY (product_id),
	CONSTRAINT ukdmlsb42a1p20vhxsahvvpexoq UNIQUE (barcode),
	CONSTRAINT ukflcbu2hb0eaxeupuejsladhxb UNIQUE (product_code),
	CONSTRAINT fk5sysu192sp9wujqpxncpm6u0s FOREIGN KEY (category_id) REFERENCES pharmacy.rdp_categories(category_id),
	CONSTRAINT fk956pamoogur3ppwmcq99vdivt FOREIGN KEY (supplier_id) REFERENCES pharmacy.rdp_suppliers(supplier_id)
);
CREATE INDEX rdp_idx_barcode ON pharmacy.rdp_products USING btree (barcode);
CREATE INDEX rdp_idx_product_code ON pharmacy.rdp_products USING btree (product_code);


-- pharmacy.rdp_purchase_orders definition

-- Drop table

-- DROP TABLE pharmacy.rdp_purchase_orders;

CREATE TABLE pharmacy.rdp_purchase_orders (
	po_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	needed_date date NULL,
	order_code varchar(50) NOT NULL,
	total_cost numeric(12, 2) NULL,
	supplier_id int8 NOT NULL,
	CONSTRAINT rdp_po_order_code UNIQUE (order_code),
	CONSTRAINT rdp_purchase_orders_pkey PRIMARY KEY (po_id),
	CONSTRAINT fkqiilvpqtcv92gaiofw4ydk570 FOREIGN KEY (supplier_id) REFERENCES pharmacy.rdp_suppliers(supplier_id)
);


-- pharmacy.rdp_user_roles definition

-- Drop table

-- DROP TABLE pharmacy.rdp_user_roles;

CREATE TABLE pharmacy.rdp_user_roles (
	user_id int8 NOT NULL,
	role_id int8 NOT NULL,
	CONSTRAINT rdp_user_roles_pkey PRIMARY KEY (user_id, role_id),
	CONSTRAINT fk3e0s9d05tq1j5sige5xvb15uc FOREIGN KEY (user_id) REFERENCES pharmacy.rdp_users(user_id),
	CONSTRAINT fk7p5dwo5d3v5xhcfb2uyrbhmfi FOREIGN KEY (role_id) REFERENCES pharmacy.rdp_roles(role_id)
);


-- pharmacy.rdp_billing_items definition

-- Drop table

-- DROP TABLE pharmacy.rdp_billing_items;

CREATE TABLE pharmacy.rdp_billing_items (
	billing_item_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	batch_no varchar(100) NULL,
	quantity int4 NOT NULL,
	subtotal numeric(12, 2) NOT NULL,
	unit_price numeric(12, 2) NOT NULL,
	billing_id int8 NOT NULL,
	product_id int8 NOT NULL,
	CONSTRAINT rdp_billing_items_pkey PRIMARY KEY (billing_item_id),
	CONSTRAINT rdp_billing_items_quantity_check CHECK ((quantity >= 1)),
	CONSTRAINT fkdveilln0ssgs74sr29elh3exa FOREIGN KEY (product_id) REFERENCES pharmacy.rdp_products(product_id),
	CONSTRAINT fkf7dqdtc9lmhvorpbg0ryybjs9 FOREIGN KEY (billing_id) REFERENCES pharmacy.rdp_billings(billing_id)
);
CREATE INDEX rdp_idx_billing_item_billing ON pharmacy.rdp_billing_items USING btree (billing_id);
CREATE INDEX rdp_idx_billing_item_product ON pharmacy.rdp_billing_items USING btree (product_id);


-- pharmacy.rdp_grns definition

-- Drop table

-- DROP TABLE pharmacy.rdp_grns;

CREATE TABLE pharmacy.rdp_grns (
	grn_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	approved_date timestamp(6) NULL,
	approved_user varchar(255) NULL,
	grn_code varchar(100) NOT NULL,
	rejected_reason varchar(255) NULL,
	status varchar(255) NOT NULL,
	po_id int8 NOT NULL,
	CONSTRAINT rdp_grn_code_idx UNIQUE (grn_code),
	CONSTRAINT rdp_grns_pkey PRIMARY KEY (grn_id),
	CONSTRAINT rdp_grns_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[]))),
	CONSTRAINT fkdeu44joas6xmk6f8h02artqy FOREIGN KEY (po_id) REFERENCES pharmacy.rdp_purchase_orders(po_id)
);


-- pharmacy.rdp_inventory_items definition

-- Drop table

-- DROP TABLE pharmacy.rdp_inventory_items;

CREATE TABLE pharmacy.rdp_inventory_items (
	inv_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	batch_no varchar(100) NULL,
	cost_price numeric(12, 2) NULL,
	price numeric(12, 2) NOT NULL,
	stock int4 NOT NULL,
	product_id int8 NOT NULL,
	CONSTRAINT rdp_inventory_items_pkey PRIMARY KEY (inv_id),
	CONSTRAINT rdp_inventory_items_stock_check CHECK ((stock >= 0)),
	CONSTRAINT uc_inventory_product_price UNIQUE (product_id, price),
	CONSTRAINT fk1dv4rqwd361ykbmw5019uovq7 FOREIGN KEY (product_id) REFERENCES pharmacy.rdp_products(product_id)
);
CREATE INDEX rdp_idx_inventory_product ON pharmacy.rdp_inventory_items USING btree (product_id);
CREATE INDEX rdp_idx_inventory_product_price ON pharmacy.rdp_inventory_items USING btree (product_id, price);


-- pharmacy.rdp_inventory_returns definition

-- Drop table

-- DROP TABLE pharmacy.rdp_inventory_returns;

CREATE TABLE pharmacy.rdp_inventory_returns (
	return_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	batch_no varchar(100) NULL,
	customer_name varchar(200) NULL,
	notes varchar(1000) NULL,
	quantity int4 NOT NULL,
	reason varchar(500) NOT NULL,
	return_date timestamp(6) NOT NULL,
	return_type varchar(20) NOT NULL,
	total_amount numeric(12, 2) NULL,
	unit_price numeric(12, 2) NOT NULL,
	product_id int8 NOT NULL,
	supplier_id int8 NULL,
	CONSTRAINT rdp_inventory_returns_pkey PRIMARY KEY (return_id),
	CONSTRAINT rdp_inventory_returns_quantity_check CHECK ((quantity >= 1)),
	CONSTRAINT rdp_inventory_returns_return_type_check CHECK (((return_type)::text = ANY ((ARRAY['FROM_CUSTOMER'::character varying, 'TO_SUPPLIER'::character varying])::text[]))),
	CONSTRAINT fk1j25jqif1axdq830mtsbv7kpr FOREIGN KEY (product_id) REFERENCES pharmacy.rdp_products(product_id),
	CONSTRAINT fkqxjbby9o6acm2e6oj5cvbiav4 FOREIGN KEY (supplier_id) REFERENCES pharmacy.rdp_suppliers(supplier_id)
);
CREATE INDEX rdp_idx_return_date ON pharmacy.rdp_inventory_returns USING btree (return_date);
CREATE INDEX rdp_idx_return_product ON pharmacy.rdp_inventory_returns USING btree (product_id);
CREATE INDEX rdp_idx_return_type ON pharmacy.rdp_inventory_returns USING btree (return_type);


-- pharmacy.rdp_purchase_order_items definition

-- Drop table

-- DROP TABLE pharmacy.rdp_purchase_order_items;

CREATE TABLE pharmacy.rdp_purchase_order_items (
	poi_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	quantity int4 NOT NULL,
	unit_cost numeric(10, 2) NULL,
	product_id int8 NOT NULL,
	po_id int8 NOT NULL,
	CONSTRAINT rdp_purchase_order_items_pkey PRIMARY KEY (poi_id),
	CONSTRAINT rdp_purchase_order_items_quantity_check CHECK ((quantity >= 1)),
	CONSTRAINT fk7prve46v8uqtmbheemoopt5ad FOREIGN KEY (product_id) REFERENCES pharmacy.rdp_products(product_id),
	CONSTRAINT fkc0o115axxabsr2xdsmlqqr38t FOREIGN KEY (po_id) REFERENCES pharmacy.rdp_purchase_orders(po_id)
);


-- pharmacy.rdp_grn_items definition

-- Drop table

-- DROP TABLE pharmacy.rdp_grn_items;

CREATE TABLE pharmacy.rdp_grn_items (
	grn_item_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	created_at timestamp(6) NOT NULL,
	created_by varchar(255) NULL,
	updated_at timestamp(6) NULL,
	updated_by varchar(255) NULL,
	"version" int8 NULL,
	received_quantity int4 NOT NULL,
	unit_cost numeric(10, 2) NULL,
	grn_id int8 NOT NULL,
	product_id int8 NOT NULL,
	price numeric(10, 2) NULL,
	CONSTRAINT rdp_grn_items_pkey PRIMARY KEY (grn_item_id),
	CONSTRAINT rdp_grn_items_received_quantity_check CHECK ((received_quantity >= 1)),
	CONSTRAINT fk5v5od8mr8miscy27ytosd5l5f FOREIGN KEY (product_id) REFERENCES pharmacy.rdp_products(product_id),
	CONSTRAINT fk7bebc0kibsravddhifnjmy8uf FOREIGN KEY (grn_id) REFERENCES pharmacy.rdp_grns(grn_id)
);

--DELETE FROM pharmacy.rdp_users   WHERE username  <> 'admin';--1

--DELETE FROM rdp_user_roles rur where rur.user_id<>1;
/*
select * from rdp_roles rr 

select * from pharmacy.rdp_users 

ALTER SEQUENCE audit_logs_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_alert_config_alert_config_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_alert_logs_alert_log_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_billing_items_billing_item_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_billings_billing_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_categories_category_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_customers_customer_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_grn_items_grn_item_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_grns_grn_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_inventory_items_inv_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_inventory_returns_return_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_products_product_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_purchase_order_items_poi_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_purchase_orders_po_id_seq RESTART WITH 1;
--ALTER SEQUENCE rdp_roles_role_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_store_settings_settings_id_seq RESTART WITH 1;
ALTER SEQUENCE rdp_suppliers_supplier_id_seq RESTART WITH 1;
ALTER SEQUENCE stock_movement_id_seq RESTART WITH 1;



TRUNCATE TABLE
  audit_logs,
  rdp_alert_config,
  rdp_alert_logs,
  rdp_billing_items,
  rdp_billings,
  rdp_categories,
  rdp_customers,
  rdp_grn_items,
  rdp_grns,
  rdp_inventory_items,
  rdp_inventory_returns,
  rdp_products,
  rdp_purchase_order_items,
  rdp_purchase_orders,
  rdp_store_settings,
  rdp_suppliers,
  stock_movement
RESTART IDENTITY CASCADE;
*/
