--
-- PostgreSQL database dump
--

\restrict c4QicBFrytMsLPhG8ZU0XUeaFyeHfTwBBPFvJKfXRmErUQgJbpC6ZsX3EiMaeRc

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

-- Started on 2025-10-13 23:41:39

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

CREATE DATABASE rdppharmacy WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_India.1252';


ALTER DATABASE rdppharmacy OWNER TO postgres;

\unrestrict c4QicBFrytMsLPhG8ZU0XUeaFyeHfTwBBPFvJKfXRmErUQgJbpC6ZsX3EiMaeRc
\connect rdppharmacy
\restrict c4QicBFrytMsLPhG8ZU0XUeaFyeHfTwBBPFvJKfXRmErUQgJbpC6ZsX3EiMaeRc

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;


CREATE TABLE public.rdp_categories (
    category_id bigint NOT NULL,
    description character varying(255),
    name character varying(100) NOT NULL
);


ALTER TABLE public.rdp_categories OWNER TO postgres;

ALTER TABLE public.rdp_categories ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rdp_categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.rdp_customers (
    customer_id bigint NOT NULL,
    address text,
    email character varying(100),
    name character varying(100) NOT NULL,
    phone character varying(20)
);


ALTER TABLE public.rdp_customers OWNER TO postgres;


ALTER TABLE public.rdp_customers ALTER COLUMN customer_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rdp_customers_customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.rdp_inventory_items (
    inv_id bigint NOT NULL,
    batch_no character varying(100),
    cost_price numeric(12,2),
    created_at timestamp(6) without time zone NOT NULL,
    price numeric(12,2) NOT NULL,
    stock integer NOT NULL,
    updated_at timestamp(6) without time zone,
    product_id bigint NOT NULL,
    CONSTRAINT rdp_inventory_items_stock_check CHECK ((stock >= 0))
);


ALTER TABLE public.rdp_inventory_items OWNER TO postgres;


ALTER TABLE public.rdp_inventory_items ALTER COLUMN inv_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rdp_inventory_items_inv_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.rdp_products (
    product_id bigint NOT NULL,
    barcode character varying(50) NOT NULL,
    bin_location character varying(50),
    expiry_date date,
    generic_name character varying(100),
    max_discount numeric(5,2),
    max_stock integer,
    min_stock integer,
    name character varying(100) NOT NULL,
    patient_instructions text,
    product_code character varying(50) NOT NULL,
    category_id bigint,
    supplier_id bigint,
    CONSTRAINT rdp_products_min_stock_check CHECK ((min_stock >= 0))
);


ALTER TABLE public.rdp_products OWNER TO postgres;


ALTER TABLE public.rdp_products ALTER COLUMN product_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rdp_products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.rdp_purchase_order_items (
    poi_id bigint NOT NULL,
    quantity integer NOT NULL,
    unit_cost numeric(10,2),
    product_id bigint NOT NULL,
    po_id bigint NOT NULL,
    CONSTRAINT rdp_purchase_order_items_quantity_check CHECK ((quantity >= 1))
);


ALTER TABLE public.rdp_purchase_order_items OWNER TO postgres;


ALTER TABLE public.rdp_purchase_order_items ALTER COLUMN poi_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rdp_purchase_order_items_poi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.rdp_purchase_orders (
    po_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    needed_date date,
    order_code character varying(30) NOT NULL,
    total_cost numeric(12,2),
    supplier_id bigint NOT NULL
);


ALTER TABLE public.rdp_purchase_orders OWNER TO postgres;

ALTER TABLE public.rdp_purchase_orders ALTER COLUMN po_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rdp_purchase_orders_po_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.rdp_roles (
    role_id bigint NOT NULL,
    role_name character varying(255) NOT NULL,
    description character varying(255)
);


ALTER TABLE public.rdp_roles OWNER TO postgres;


CREATE SEQUENCE public.rdp_roles_role_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.rdp_roles_role_id_seq OWNER TO postgres;


ALTER SEQUENCE public.rdp_roles_role_id_seq OWNED BY public.rdp_roles.role_id;


CREATE TABLE public.rdp_suppliers (
    supplier_id bigint NOT NULL,
    contact_info character varying(255),
    name character varying(100) NOT NULL
);


ALTER TABLE public.rdp_suppliers OWNER TO postgres;


ALTER TABLE public.rdp_suppliers ALTER COLUMN supplier_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rdp_suppliers_supplier_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public.rdp_user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);


ALTER TABLE public.rdp_user_roles OWNER TO postgres;


CREATE TABLE public.rdp_users (
    user_id bigint NOT NULL,
    username character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.rdp_users OWNER TO postgres;



CREATE SEQUENCE public.rdp_users_user_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.rdp_users_user_id_seq OWNER TO postgres;


ALTER SEQUENCE public.rdp_users_user_id_seq OWNED BY public.rdp_users.user_id;


ALTER TABLE ONLY public.rdp_roles ALTER COLUMN role_id SET DEFAULT nextval('public.rdp_roles_role_id_seq'::regclass);


ALTER TABLE ONLY public.rdp_users ALTER COLUMN user_id SET DEFAULT nextval('public.rdp_users_user_id_seq'::regclass);


INSERT INTO public.rdp_roles (role_id, role_name, description) VALUES (1, 'admin', 'Administrator with full access');
INSERT INTO public.rdp_roles (role_id, role_name, description) VALUES (2, 'pharmacist', 'Pharmacist with limited access');
INSERT INTO public.rdp_roles (role_id, role_name, description) VALUES (3, 'manager', 'Manager with reporting access');



INSERT INTO public.rdp_user_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO public.rdp_user_roles (user_id, role_id) VALUES (2, 2);
INSERT INTO public.rdp_user_roles (user_id, role_id) VALUES (3, 3);



INSERT INTO public.rdp_users (user_id, username, password_hash, created_at) VALUES (1, 'admin', '$2a$10$R9h/cIPz0gi.URNNX3kh2Okh.XdJ17SSfuQpq.z65xQQruVd/on5O', '2025-10-13 23:20:11.297036');
INSERT INTO public.rdp_users (user_id, username, password_hash, created_at) VALUES (2, 'pharmacist', '$2a$10$R9h/cIPz0gi.URNNX3kh2Okh.XdJ17SSfuQpq.z65xQQruVd/on5O', '2025-10-13 23:21:00.581395');
INSERT INTO public.rdp_users (user_id, username, password_hash, created_at) VALUES (3, 'manager', '$2a$10$R9h/cIPz0gi.URNNX3kh2Okh.XdJ17SSfuQpq.z65xQQruVd/on5O', '2025-10-13 23:23:44.795215');


SELECT pg_catalog.setval('public.rdp_categories_category_id_seq', 1, false);


SELECT pg_catalog.setval('public.rdp_customers_customer_id_seq', 1, false);


SELECT pg_catalog.setval('public.rdp_inventory_items_inv_id_seq', 1, false);


SELECT pg_catalog.setval('public.rdp_products_product_id_seq', 1, false);


SELECT pg_catalog.setval('public.rdp_purchase_order_items_poi_id_seq', 1, false);


SELECT pg_catalog.setval('public.rdp_purchase_orders_po_id_seq', 1, false);


SELECT pg_catalog.setval('public.rdp_roles_role_id_seq', 3, true);


SELECT pg_catalog.setval('public.rdp_suppliers_supplier_id_seq', 1, false);


SELECT pg_catalog.setval('public.rdp_users_user_id_seq', 3, true);


ALTER TABLE ONLY public.rdp_categories
    ADD CONSTRAINT rdp_categories_pkey PRIMARY KEY (category_id);


ALTER TABLE ONLY public.rdp_customers
    ADD CONSTRAINT rdp_customers_pkey PRIMARY KEY (customer_id);


ALTER TABLE ONLY public.rdp_inventory_items
    ADD CONSTRAINT rdp_inventory_items_pkey PRIMARY KEY (inv_id);


ALTER TABLE ONLY public.rdp_purchase_orders
    ADD CONSTRAINT rdp_po_order_code UNIQUE (order_code);


ALTER TABLE ONLY public.rdp_products
    ADD CONSTRAINT rdp_products_pkey PRIMARY KEY (product_id);


ALTER TABLE ONLY public.rdp_purchase_order_items
    ADD CONSTRAINT rdp_purchase_order_items_pkey PRIMARY KEY (poi_id);


ALTER TABLE ONLY public.rdp_purchase_orders
    ADD CONSTRAINT rdp_purchase_orders_pkey PRIMARY KEY (po_id);


ALTER TABLE ONLY public.rdp_roles
    ADD CONSTRAINT rdp_roles_pkey PRIMARY KEY (role_id);


ALTER TABLE ONLY public.rdp_roles
    ADD CONSTRAINT rdp_roles_role_name_key UNIQUE (role_name);


ALTER TABLE ONLY public.rdp_suppliers
    ADD CONSTRAINT rdp_suppliers_pkey PRIMARY KEY (supplier_id);


ALTER TABLE ONLY public.rdp_user_roles
    ADD CONSTRAINT rdp_user_roles_pkey PRIMARY KEY (user_id, role_id);


ALTER TABLE ONLY public.rdp_users
    ADD CONSTRAINT rdp_users_pkey PRIMARY KEY (user_id);


ALTER TABLE ONLY public.rdp_users
    ADD CONSTRAINT rdp_users_username_key UNIQUE (username);


ALTER TABLE ONLY public.rdp_customers
    ADD CONSTRAINT uk48jywia10yof5d274fu3sxosr UNIQUE (email);


ALTER TABLE ONLY public.rdp_products
    ADD CONSTRAINT ukdmlsb42a1p20vhxsahvvpexoq UNIQUE (barcode);


ALTER TABLE ONLY public.rdp_customers
    ADD CONSTRAINT ukdp80l2pqpgqwqpmhyi837iw9s UNIQUE (phone);


ALTER TABLE ONLY public.rdp_products
    ADD CONSTRAINT ukflcbu2hb0eaxeupuejsladhxb UNIQUE (product_code);


CREATE INDEX rdp_idx_barcode ON public.rdp_products USING btree (barcode);


CREATE INDEX rdp_idx_inventory_product ON public.rdp_inventory_items USING btree (product_id);


CREATE INDEX rdp_idx_inventory_product_price ON public.rdp_inventory_items USING btree (product_id, price);


CREATE INDEX rdp_idx_product_code ON public.rdp_products USING btree (product_code);


ALTER TABLE ONLY public.rdp_inventory_items
    ADD CONSTRAINT fk1dv4rqwd361ykbmw5019uovq7 FOREIGN KEY (product_id) REFERENCES public.rdp_products(product_id);


ALTER TABLE ONLY public.rdp_products
    ADD CONSTRAINT fk5sysu192sp9wujqpxncpm6u0s FOREIGN KEY (category_id) REFERENCES public.rdp_categories(category_id);


ALTER TABLE ONLY public.rdp_purchase_order_items
    ADD CONSTRAINT fk7prve46v8uqtmbheemoopt5ad FOREIGN KEY (product_id) REFERENCES public.rdp_products(product_id);


ALTER TABLE ONLY public.rdp_products
    ADD CONSTRAINT fk956pamoogur3ppwmcq99vdivt FOREIGN KEY (supplier_id) REFERENCES public.rdp_suppliers(supplier_id);


ALTER TABLE ONLY public.rdp_purchase_order_items
    ADD CONSTRAINT fkc0o115axxabsr2xdsmlqqr38t FOREIGN KEY (po_id) REFERENCES public.rdp_purchase_orders(po_id);


ALTER TABLE ONLY public.rdp_purchase_orders
    ADD CONSTRAINT fkqiilvpqtcv92gaiofw4ydk570 FOREIGN KEY (supplier_id) REFERENCES public.rdp_suppliers(supplier_id);



ALTER TABLE ONLY public.rdp_user_roles
    ADD CONSTRAINT rdp_user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.rdp_roles(role_id);



ALTER TABLE ONLY public.rdp_user_roles
    ADD CONSTRAINT rdp_user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.rdp_users(user_id);


-- Completed on 2025-10-13 23:41:40

--
-- PostgreSQL database dump complete
--

\unrestrict c4QicBFrytMsLPhG8ZU0XUeaFyeHfTwBBPFvJKfXRmErUQgJbpC6ZsX3EiMaeRc

