package com.rdp.model;

public enum MovementReasonType {
    PURCHASE,
    SALE,
    RETURN,
    PHYSICAL_COUNT_ADJUSTMENT,
    INVENTORY_COUNT_RECONCILIATION,
    EXPIRY_ADJUSTMENT,
    DAMAGED_ADJUSTMENT,
    SUPPLIER_RETURN,
    CUSTOMER_RETURN,
    STOCK_TRANSFER,
    MANUAL_ADJUSTMENT,
    OTHER
}
